name: Build and push

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:db-backup"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBE_VERSION=1.23.4
            HELM_VERSION=3.8.1
          tags: cliffred/db-backup:latest
